apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    wave.pusher.com/update-on-config-change: "true"
  labels:
    app: http-cache-controller
  name: http-cache-controller
spec:
  replicas: 1
  serviceName: http-cache-controller
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: http-cache-controller
  template:
    metadata:
      labels:
        app: http-cache-controller
        group: streaming
    spec:
      containers:
        - image: swisstxt/http-cache-controller:master
          imagePullPolicy: Always
          name: nginx
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 250m
              ephemeral-storage: 10Mi
              memory: 256Mi
          securityContext:
            runAsUser: 1000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: http-cache-controller
      securityContext: {}

